name: pymanuf CI (Lint & Test)

on:
    push:
    pull_request:
    workflow_run:
        workflows: ["Update manufacturer file"]
        types: [completed]

jobs:
  black_formatter:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [black_formatter]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: python -m unittest discover tests
